{
  "openapi": "3.0.2",
  "info": {
    "title": "Donation Tracker API",
    "description": "RTA in JapanがforkしたDonation TrackerのAPI仕様",
    "version": "1.0.0"
  },
  "externalDocs": {
    "description": "開発リポジトリ",
    "url": "https://github.com/rtainjapan/donation-tracker"
  },
  "servers": [
    {
      "url": "https://tracker.rtain.jp/"
    }
  ],
  "paths": {
    "/api/v1/search/?type=bid": {
      "get": {
        "description": "投票情報。親要素だけ返ってくる。",
        "tags": ["search"],
        "parameters": [
          {
            "in": "query",
            "name": "event",
            "required": false,
            "description": "イベントID",
            "schema": {
              "type": "number",
              "example": "4"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/trackerBids"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/search/?type=bidtarget": {
      "get": {
        "description": "投票情報。投票対象となる子要素だけ返ってくる。QueryはそれぞれのAnd条件なので、矛盾した指定の仕方をすると空配列になる。",
        "tags": ["search"],
        "parameters": [
          {
            "in": "query",
            "name": "event",
            "required": false,
            "description": "イベントID",
            "schema": {
              "type": "number",
              "example": 4
            }
          },
          {
            "in": "query",
            "name": "run",
            "required": false,
            "description": "RTAのID",
            "schema": {
              "type": "number",
              "example": 138
            }
          },
          {
            "in": "query",
            "name": "parent",
            "required": false,
            "description": "親のBidWarのID。これに紐づく要素だけ返ってくる",
            "schema": {
              "type": "number",
              "example": 111
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/trackerBidChildren"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/search/?type=donation": {
      "get": {
        "description": "寄付情報を取得",
        "tags": ["search"],
        "parameters": [
          {
            "in": "query",
            "name": "all_comments",
            "required": false,
            "description": "プライバシーフィルターを通すかどうか。値はなくて、クエリにkeyがあるか無いかで判定される。指定した場合はログインが必要",
            "schema": {
              "type": "string",
              "example": ""
            }
          },
          {
            "in": "query",
            "name": "feed",
            "required": false,
            "description": "toprocess: コメント未処理の寄付情報に絞り込む",
            "schema": {
              "type": "string",
              "example": "toprocess"
            }
          },
          {
            "in": "query",
            "name": "event",
            "required": false,
            "description": "イベントID",
            "schema": {
              "type": "number",
              "example": "4"
            }
          },
          {
            "in": "cookie",
            "name": "csrftoken",
            "required": false,
            "description": "CSRFトークン。all_commentsを指定するなら必要",
            "schema": {
              "type": "string",
              "example": "1234567890asdfghjk; sessionid=zxcvbnm,.lkjhgfdsa;"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/trackerDonations"
                },
                "examples": {
                  "response1": {
                    "$ref": "#/components/examples/donationResponse1"
                  },
                  "response2": {
                    "$ref": "#/components/examples/donationResponse2"
                  },
                  "response3": {
                    "$ref": "#/components/examples/donationResponse3"
                  }
                }
              }
            }
          },
          "403": {
            "description": "認証されてない",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/errorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/search/?type=donor": {
      "get": {
        "description": "寄付者情報を取得",
        "tags": ["search"],
        "parameters": [
          {
            "in": "cookie",
            "name": "csrftoken",
            "required": false,
            "description": "CSRFトークン。all_commentsを指定するなら必要",
            "schema": {
              "type": "string",
              "example": "1234567890asdfghjk; sessionid=zxcvbnm,.lkjhgfdsa;"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/trackerDonors"
                }
              }
            }
          },
          "403": {
            "description": "認証されてない",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/errorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/search/?type=milestone": {
      "get": {
        "description": "",
        "tags": ["search"],
        "parameters": [
          {
            "in": "cookie",
            "name": "csrftoken",
            "required": false,
            "description": "CSRFトークン。all_commentsを指定するなら必要",
            "schema": {
              "type": "string",
              "example": "1234567890asdfghjk; sessionid=zxcvbnm,.lkjhgfdsa;"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {}
            }
          },
          "403": {
            "description": "認証されてない",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/errorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/search/?type=event": {
      "get": {
        "description": "",
        "tags": ["search"],
        "parameters": [
          {
            "in": "cookie",
            "name": "csrftoken",
            "required": false,
            "description": "CSRFトークン。all_commentsを指定するなら必要",
            "schema": {
              "type": "string",
              "example": "1234567890asdfghjk; sessionid=zxcvbnm,.lkjhgfdsa;"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/trackerEvents"
                }
              }
            }
          },
          "403": {
            "description": "認証されてない",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/errorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/search/?type=prize": {
      "get": {
        "description": "",
        "tags": ["search"],
        "parameters": [
          {
            "in": "cookie",
            "name": "csrftoken",
            "required": false,
            "description": "CSRFトークン。all_commentsを指定するなら必要",
            "schema": {
              "type": "string",
              "example": "1234567890asdfghjk; sessionid=zxcvbnm,.lkjhgfdsa;"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {}
            }
          },
          "403": {
            "description": "認証されてない",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/errorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/search/?type=run": {
      "get": {
        "description": "イベントのゲーム情報を取得",
        "tags": ["search"],
        "parameters": [
          {
            "in": "query",
            "name": "event",
            "required": false,
            "description": "イベントID",
            "schema": {
              "type": "number",
              "example": "4"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/trackerRuns"
                },
                "examples": {
                  "response1": {
                    "$ref": "#/components/examples/runResponse1"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/search/?type=runner": {
      "get": {
        "description": "",
        "tags": ["search"],
        "parameters": [
          {
            "in": "cookie",
            "name": "csrftoken",
            "required": false,
            "description": "CSRFトークン。all_commentsを指定するなら必要",
            "schema": {
              "type": "string",
              "example": "1234567890asdfghjk; sessionid=zxcvbnm,.lkjhgfdsa;"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/trackerRunners"
                }
              }
            }
          },
          "403": {
            "description": "認証されてない",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/errorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/edit/": {
      "post": {
        "description": "寄付のコメント承認",
        "tags": ["edit"],
        "parameters": [
          {
            "in": "header",
            "name": "X-CSRFToken",
            "schema": {
              "type": "string",
              "description": "Cookieに入ってるcsrftokenと同じ",
              "example": "ABCDEFG123456"
            }
          },
          {
            "in": "cookie",
            "name": "csrftoken",
            "schema": {
              "type": "string",
              "description": "CSRFトークン",
              "example": "ABCDEFG123456; sessionid=1234567890;"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "required": true,
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/trackerEditDonation"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/trackerDonations"
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/errorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/delete/": {
      "post": {
        "description": "要素の削除",
        "tags": ["delete"],
        "parameters": [
          {
            "in": "header",
            "name": "X-CSRFToken",
            "schema": {
              "type": "string",
              "description": "Cookieに入ってるcsrftokenと同じ",
              "example": "ABCDEFG123456"
            }
          },
          {
            "in": "cookie",
            "name": "csrftoken",
            "schema": {
              "type": "string",
              "description": "CSRFトークン",
              "example": "ABCDEFG123456; sessionid=1234567890;"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "required": true,
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/trackerDelete"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "Object 3 of type event deleted"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/errorResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "trackerBids": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/trackerBid"
        }
      },
      "trackerBid": {
        "type": "object",
        "properties": {
          "model": {
            "type": "string",
            "example": "tracker.bid"
          },
          "pk": {
            "type": "integer",
            "example": 5
          },
          "fields": {
            "type": "object",
            "properties": {
              "allowuseroptions": {
                "type": "boolean",
                "description": "",
                "example": false
              },
              "biddependency": {
                "type": "integer",
                "description": "無い時はnull",
                "example": null
              },
              "canonical_url": {
                "type": "string",
                "description": "Bid WarのURL",
                "example": "https://tracker.rtain.jp/bid/1"
              },
              "count": {
                "type": "integer",
                "description": "投票数",
                "example": 21
              },
              "description": {
                "type": "string",
                "description": "Bid Warの詳細文",
                "example": "走者2名が持つマグカップのカラーを何にしますか？"
              },
              "event": {
                "type": "integer",
                "description": "イベントID",
                "example": 4
              },
              "event__canonical_url": {
                "type": "string",
                "description": "イベントのURL",
                "example": "https://tracker.rtain.jp/event/2"
              },
              "event__datetime": {
                "type": "string",
                "description": "イベントの開始時刻",
                "example": "2021-12-26T03:00:00Z"
              },
              "event__name": {
                "type": "string",
                "description": "イベント名",
                "example": "RTA in Japan Winter 2021"
              },
              "event__public": {
                "type": "string",
                "description": "イベント名",
                "example": "RTA in Japan Winter 2021"
              },
              "event__short": {
                "type": "string",
                "description": "URLとかに使われる短いやつ",
                "example": "rtaijw2021"
              },
              "event__timezone": {
                "type": "string",
                "description": "イベントのタイムゾーン",
                "example": "Asia/Tokyo"
              },
              "goal": {
                "type": "integer",
                "description": "目標金額。無い時はnull",
                "example": 1000
              },
              "istarget": {
                "type": "boolean",
                "description": "寄付受付対象の項目であるかどうか。親子関係の末端の要素がtrueになる。",
                "example": false
              },
              "name": {
                "type": "string",
                "description": "",
                "example": "マグカップの色"
              },
              "option_max_length": {
                "type": "integer",
                "description": "",
                "example": null
              },
              "parent": {
                "type": "integer",
                "description": "親のID。自身が親の時はnull",
                "example": null
              },
              "public": {
                "type": "string",
                "description": "",
                "example": "Don't Spill Your Coffee Any% (Run) -- マグカップの色"
              },
              "revealedtime": {
                "type": "string",
                "description": "寄付の受付開始時刻",
                "example": "2021-12-25T03:00:00Z"
              },
              "shortdescription": {
                "type": "string",
                "description": "主にNodeCGとかで表示する時に使う",
                "example": "マグカップの色は？"
              },
              "speedrun": {
                "type": "integer",
                "description": "RTAのID",
                "example": 1
              },
              "speedrun__canonical_url": {
                "type": "string",
                "description": "RTAのURL",
                "example": "https://tracker.rtain.jp/run/1"
              },
              "speedrun__display_name": {
                "type": "string",
                "description": "「ゲーム名 カテゴリ名」の形式",
                "example": "Don't Spill Your Coffee Any%"
              },
              "speedrun__endtime": {
                "type": "string",
                "description": "RTAの終了日時",
                "example": "2021-12-26T10:32:00Z"
              },
              "speedrun__name": {
                "type": "string",
                "description": "",
                "example": "Don't Spill Your Coffee"
              },
              "speedrun__order": {
                "type": "integer",
                "description": "スケジュールでの並び順。未指定の場合はnull",
                "example": 6
              },
              "speedrun__public": {
                "type": "string",
                "description": "",
                "example": "Don't Spill Your Coffee Any% (event_id: 2)"
              },
              "speedrun__starttime": {
                "type": "string",
                "description": "RTAの開始日時",
                "example": "2021-12-26T10:14:00Z"
              },
              "speedrun__twitch_name": {
                "type": "string",
                "description": "Twitchでのゲーム名。今はゲームIDを入れる用途で使ってる",
                "example": "12345"
              },
              "state": {
                "type": "string",
                "description": "",
                "example": "CLOSED"
              },
              "total": {
                "type": "integer",
                "description": "合計金額",
                "example": 48394
              }
            }
          }
        }
      },
      "trackerBidChildren": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/trackerBidChild"
        }
      },
      "trackerBidChild": {
        "type": "object",
        "properties": {
          "model": {
            "type": "string",
            "example": "tracker.bid"
          },
          "pk": {
            "type": "integer",
            "example": 5
          },
          "fields": {
            "type": "object",
            "properties": {
              "allowuseroptions": {
                "type": "boolean",
                "description": "",
                "example": false
              },
              "biddependency": {
                "type": "integer",
                "description": "無い時はnull",
                "example": null
              },
              "canonical_url": {
                "type": "string",
                "description": "Bid WarのURL",
                "example": "https://tracker.rtain.jp/bid/1"
              },
              "count": {
                "type": "integer",
                "description": "投票数",
                "example": 21
              },
              "description": {
                "type": "string",
                "description": "Bid Warの詳細文",
                "example": "走者2名が持つマグカップのカラーを何にしますか？"
              },
              "event": {
                "type": "integer",
                "description": "イベントID",
                "example": 4
              },
              "event__canonical_url": {
                "type": "string",
                "description": "イベントのURL",
                "example": "https://tracker.rtain.jp/event/2"
              },
              "event__datetime": {
                "type": "string",
                "description": "イベントの開始時刻",
                "example": "2021-12-26T03:00:00Z"
              },
              "event__name": {
                "type": "string",
                "description": "イベント名",
                "example": "RTA in Japan Winter 2021"
              },
              "event__public": {
                "type": "string",
                "description": "イベント名",
                "example": "RTA in Japan Winter 2021"
              },
              "event__short": {
                "type": "string",
                "description": "URLとかに使われる短いやつ",
                "example": "rtaijw2021"
              },
              "event__timezone": {
                "type": "string",
                "description": "イベントのタイムゾーン",
                "example": "Asia/Tokyo"
              },
              "goal": {
                "type": "integer",
                "description": "目標金額。無い時はnull",
                "example": 1000
              },
              "istarget": {
                "type": "boolean",
                "description": "寄付受付対象の項目であるかどうか。親子関係の末端の要素がtrueになる。",
                "example": true
              },
              "name": {
                "type": "string",
                "description": "",
                "example": "マグカップの色"
              },
              "option_max_length": {
                "type": "integer",
                "description": "",
                "example": null
              },
              "parent": {
                "type": "integer",
                "description": "親のID。自身が親の時はnull",
                "example": 111
              },
              "parent__allowuseroptions": {
                "type": "boolean",
                "description": "",
                "example": false
              },
              "parent__canonical_url": {
                "type": "string",
                "description": "",
                "example": "https://tracker.rtain.jp/bid/111"
              },
              "parent__count": {
                "type": "integer",
                "description": "",
                "example": 81
              },
              "parent__event__canonical_url": {
                "type": "string",
                "description": "",
                "example": "https://tracker.rtain.jp/event/4"
              },
              "parent__event__datetime": {
                "type": "string",
                "description": "",
                "example": "2022-08-11T03:00:00Z"
              },
              "parent__event__name": {
                "type": "string",
                "description": "",
                "example": "RTA in Japan Summer 2022"
              },
              "parent__event__public": {
                "type": "string",
                "description": "",
                "example": "RTA in Japan Summer 2022"
              },
              "parent__event__short": {
                "type": "string",
                "description": "",
                "example": "rtaijs2022"
              },
              "parent__event__timezone": {
                "type": "string",
                "description": "",
                "example": "Asia/Tokyo"
              },
              "parent__goal": {
                "type": "integer",
                "description": "",
                "example": null
              },
              "parent__name": {
                "type": "string",
                "description": "",
                "example": "プレイ中の目隠し"
              },
              "parent__option_max_length": {
                "type": "integer",
                "description": "",
                "example": null
              },
              "parent__public": {
                "type": "string",
                "description": "",
                "example": "大乱闘スマッシュブラザーズDX 目隠し アドベンチャー モード (Run) -- プレイ中の目隠し"
              },
              "parent__state": {
                "type": "string",
                "description": "",
                "example": "CLOSED"
              },
              "parent__total": {
                "type": "integer",
                "description": "",
                "example": 188807
              },
              "public": {
                "type": "string",
                "description": "",
                "example": "Don't Spill Your Coffee Any% (Run) -- マグカップの色"
              },
              "revealedtime": {
                "type": "string",
                "description": "寄付の受付開始時刻",
                "example": "2021-12-25T03:00:00Z"
              },
              "shortdescription": {
                "type": "string",
                "description": "主にNodeCGとかで表示する時に使う",
                "example": "マグカップの色は？"
              },
              "speedrun": {
                "type": "integer",
                "description": "RTAのID",
                "example": 1
              },
              "speedrun__canonical_url": {
                "type": "string",
                "description": "RTAのURL",
                "example": "https://tracker.rtain.jp/run/1"
              },
              "speedrun__display_name": {
                "type": "string",
                "description": "「ゲーム名 カテゴリ名」の形式",
                "example": "Don't Spill Your Coffee Any%"
              },
              "speedrun__endtime": {
                "type": "string",
                "description": "RTAの終了日時",
                "example": "2021-12-26T10:32:00Z"
              },
              "speedrun__name": {
                "type": "string",
                "description": "",
                "example": "Don't Spill Your Coffee"
              },
              "speedrun__order": {
                "type": "integer",
                "description": "スケジュールでの並び順。未指定の場合はnull",
                "example": 6
              },
              "speedrun__public": {
                "type": "string",
                "description": "",
                "example": "Don't Spill Your Coffee Any% (event_id: 2)"
              },
              "speedrun__starttime": {
                "type": "string",
                "description": "RTAの開始日時",
                "example": "2021-12-26T10:14:00Z"
              },
              "speedrun__twitch_name": {
                "type": "string",
                "description": "Twitchでのゲーム名。今はゲームIDを入れる用途で使ってる",
                "example": "12345"
              },
              "state": {
                "type": "string",
                "description": "",
                "example": "CLOSED"
              },
              "total": {
                "type": "integer",
                "description": "合計金額",
                "example": 48394
              }
            }
          }
        }
      },
      "trackerDonations": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/trackerDonation"
        }
      },
      "trackerDonation": {
        "type": "object",
        "properties": {
          "model": {
            "type": "string",
            "example": "tracker.donation"
          },
          "pk": {
            "type": "integer",
            "example": 5
          },
          "fields": {
            "type": "object",
            "properties": {
              "donor": {
                "type": "integer",
                "description": "寄付者固有のID",
                "example": 1
              },
              "event": {
                "type": "integer",
                "description": "イベントID",
                "example": 4
              },
              "domain": {
                "type": "string",
                "description": "どこで寄付したか",
                "example": "PAYPAL"
              },
              "transactionstate": {
                "type": "string",
                "description": "寄付のトランザクション状態",
                "enum": ["PENDING", "COMPLETED", "CANCELLED", "FLAGGED"],
                "example": "COMPLETED"
              },
              "readstate": {
                "type": "string",
                "description": "",
                "example": "PENDING",
                "enum": ["PENDING", "READYTOREAD", "IGNORED", "READ", "FLAGGED"]
              },
              "commentstate": {
                "type": "string",
                "description": "コメントの承認状態。コメント無しはABSENT",
                "example": "APPROVED",
                "enum": ["ABSENT", "PENDING", "DENIED", "APPROVED", "FLAGGED"]
              },
              "amount": {
                "type": "number",
                "description": "金額。日本円でも小数点以下が含まれる",
                "example": 2500.0
              },
              "currency": {
                "type": "string",
                "description": "単位",
                "example": "JPY"
              },
              "timereceived": {
                "type": "string",
                "description": "タイムスタンプ",
                "example": "2022-08-13T19:44:20.472Z"
              },
              "comment": {
                "type": "string",
                "description": "コメント。all_commentsを指定しないと載らない",
                "example": "応援してます！"
              },
              "commentlanguage": {
                "type": "string",
                "description": "コメントの言語。all_commentsを指定しないと載らない",
                "example": "un"
              },
              "pinned": {
                "type": "boolean",
                "description": "",
                "example": false
              },
              "canonical_url": {
                "type": "string",
                "description": "各寄付のURL",
                "example": "https://tracker.rtain.jp/donation/5"
              },
              "public": {
                "type": "string",
                "description": "名前、金額、タイムスタンプ",
                "example": "Rちゃん (2500.0) 2022-08-13T19:44:20.472Z"
              },
              "donor__alias": {
                "type": "string",
                "description": "寄付者名",
                "example": "Rちゃん"
              },
              "donor__alias_num": {
                "type": "integer",
                "description": "",
                "example": 5
              },
              "donor__visibility": {
                "type": "string",
                "description": "",
                "example": "ALIAS"
              },
              "donor__canonical_url": {
                "type": "string",
                "description": "各寄付者のURL",
                "example": "https://tracker.rtain.jp/donor/1"
              },
              "donor__public": {
                "type": "string",
                "description": "寄付者名",
                "example": "Rちゃん"
              }
            }
          }
        }
      },
      "trackerDonors": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/trackerDonor"
        }
      },
      "trackerDonor": {
        "type": "object",
        "properties": {
          "model": {
            "type": "string",
            "example": "tracker.donor"
          },
          "pk": {
            "type": "integer",
            "example": 5
          },
          "fields": {
            "type": "object",
            "properties": {
              "alias": {
                "type": "string",
                "description": "",
                "example": "Rちゃん"
              },
              "alias_num": {
                "type": "integer",
                "description": "",
                "example": 7144
              },
              "canonical_url": {
                "type": "string",
                "description": "寄付者のURL",
                "example": "https://tracker.rtain.jp/donor/5"
              },
              "public": {
                "type": "string",
                "description": "名前",
                "example": "Rちゃん"
              },
              "visibility": {
                "type": "string",
                "description": "",
                "example": "ALIAS"
              }
            }
          }
        }
      },
      "trackerEvents": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/trackerEvent"
        }
      },
      "trackerEvent": {
        "properties": {
          "model": {
            "type": "string",
            "example": "tracker.event"
          },
          "pk": {
            "type": "integer",
            "example": 1
          },
          "fields": {
            "type": "object",
            "properties": {
              "allow_donations": {
                "type": "boolean",
                "description": "寄付を受け付けているかどうか",
                "example": false
              },
              "allowed_prize_countries": {
                "type": "array",
                "description": "",
                "example": []
              },
              "amount": {
                "type": "integer",
                "description": "",
                "example": 6017034
              },
              "avg": {
                "type": "number",
                "description": "",
                "example": 1859.4048207663782
              },
              "canonical_url": {
                "type": "string",
                "description": "イベントのURL",
                "example": "https://tracker.rtain.jp/event/1"
              },
              "count": {
                "type": "integer",
                "description": "寄付数",
                "example": 3236
              },
              "datetime": {
                "type": "string",
                "description": "イベントの開始日時",
                "example": "2021-08-11T03:00:00Z"
              },
              "disallowed_prize_regions": {
                "type": "array",
                "description": "",
                "example": []
              },
              "hashtag": {
                "type": "string",
                "description": "",
                "example": "RTAinJapan"
              },
              "locked": {
                "type": "boolean",
                "description": "",
                "example": true
              },
              "max": {
                "type": "number",
                "description": "最大寄付額",
                "example": 95000
              },
              "minimumdonation": {
                "type": "number",
                "description": "最小寄付額",
                "example": 100
              },
              "name": {
                "type": "string",
                "description": "",
                "example": "RTA in Japan Summer 2021"
              },
              "paypalcurrency": {
                "type": "string",
                "description": "通貨単位",
                "example": "JPY"
              },
              "paypalemail": {
                "type": "string",
                "description": "PayPal寄付先のメールアドレス",
                "example": "hogehoge@example.com"
              },
              "public": {
                "type": "string",
                "description": "",
                "example": "RTA in Japan Summer 2021"
              },
              "receivername": {
                "type": "string",
                "description": "寄付先団体名",
                "example": "寄付先団体名"
              },
              "short": {
                "type": "string",
                "description": "イベントURLとかで使われる短いやつ",
                "example": "rtaij2021s"
              },
              "targetamount": {
                "type": "number",
                "description": "目標金額",
                "example": 100000000
              },
              "timezone": {
                "type": "string",
                "description": "タイムゾーン",
                "example": "Asia/Tokyo"
              },
              "use_one_step_screening": {
                "type": "boolean",
                "description": "寄付画面で1stepでの寄付にするかどうか",
                "example": true
              }
            }
          }
        }
      },
      "trackerRuns": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/trackerRun"
        }
      },
      "trackerRun": {
        "properties": {
          "model": {
            "type": "string",
            "example": "tracker.speedrun"
          },
          "pk": {
            "type": "integer",
            "example": 5
          },
          "fields": {
            "type": "object",
            "properties": {
              "canonical_url": {
                "type": "string",
                "description": "各スピードランののURL",
                "example": "https://tracker.rtain.jp/run/5"
              },
              "category": {
                "type": "string",
                "description": "カテゴリ",
                "example": "Any%"
              },
              "commentators": {
                "type": "string",
                "description": "解説者。現状のtrackerには値が入ってない",
                "example": "Rちゃん"
              },
              "console": {
                "type": "string",
                "description": "機種名",
                "example": "PlayStation 4"
              },
              "coop": {
                "type": "boolean",
                "description": "協力プレイかどうか。今のRiJは使ってない",
                "example": true
              },
              "deprecated_runners": {
                "type": "string",
                "description": "走者名。複数いる場合は、カンマスペースで区切って並べる",
                "example": "RTAちゃん, Rくん"
              },
              "description": {
                "type": "string",
                "description": "詳細説明",
                "example": "なんやかんや"
              },
              "display_name": {
                "type": "string",
                "description": "表示名。「ゲーム名 カテゴリ名」の形式",
                "example": "地球防衛軍5 Any%"
              },
              "endtime": {
                "type": "string",
                "description": "終了時刻",
                "example": "2022-08-11T04:20:00Z"
              },
              "event": {
                "type": "integer",
                "description": "イベントID",
                "example": 4
              },
              "giantbomb_id": {
                "type": "string",
                "description": "GiantBomb databaseでのID。無い場合はnull",
                "example": null
              },
              "name": {
                "type": "string",
                "description": "ゲーム名",
                "example": "地球防衛軍５"
              },
              "order": {
                "type": "integer",
                "description": "スケジュールでの並び順。未指定の場合はnull",
                "example": 1
              },
              "public": {
                "type": "string",
                "description": "ゲーム名、カテゴリ名、イベントID",
                "example": "地球防衛軍5 Any% (event_id: 4)"
              },
              "release_year": {
                "type": "integer",
                "description": "リリース年",
                "example": 2007
              },
              "run_time": {
                "type": "string",
                "description": "いわゆるEST",
                "example": "1:05:00"
              },
              "runners": {
                "type": "array",
                "description": "走者IDのリスト",
                "items": {
                  "type": "integer",
                  "example": 166
                }
              },
              "setup_time": {
                "type": "string",
                "description": "セットアップタイム",
                "example": "0:15:00"
              },
              "starttime": {
                "type": "string",
                "description": "開始時刻",
                "example": "2022-08-11T03:00:00Z"
              },
              "twitch_name": {
                "type": "string",
                "description": "Twitchでのゲーム名。今はゲームIDを入れる用途で使ってる",
                "example": "493080"
              }
            }
          }
        }
      },
      "trackerRunners": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/trackerRunner"
        }
      },
      "trackerRunner": {
        "properties": {
          "model": {
            "type": "string",
            "example": "tracker.runner"
          },
          "pk": {
            "type": "integer",
            "example": 5
          },
          "fields": {
            "type": "object",
            "properties": {
              "donor": {
                "type": "integer",
                "description": "寄付者と繋げるためのID。現状はみんなnull",
                "example": null
              },
              "name": {
                "type": "string",
                "description": "走者名",
                "example": "RTAちゃん"
              },
              "nico": {
                "type": "string",
                "description": "ニコニココミュニティID",
                "example": "co12345678"
              },
              "platform": {
                "type": "string",
                "description": "配信プラットフォーム",
                "example": "TWITCH",
                "enum": ["TWTICH", "MIXER", "FACEBOOK", "YOUTUBE", "NICONICO"]
              },
              "pronouns": {
                "type": "string",
                "description": "he/him, she/her, they/themとかのアレ",
                "example": ""
              },
              "public": {
                "type": "string",
                "description": "",
                "example": "RTAちゃん"
              },
              "stream": {
                "type": "string",
                "description": "",
                "example": ""
              },
              "twitch": {
                "type": "string",
                "description": "TwitchID",
                "example": "rta_chan"
              },
              "twitter": {
                "type": "string",
                "description": "TwitterID。@無し",
                "example": "rta_chan"
              },
              "youtube": {
                "type": "string",
                "description": "YoutubeチャンネルID",
                "example": ""
              }
            }
          }
        }
      },
      "trackerEditDonation": {
        "type": "object",
        "properties": {
          "commentstate": {
            "type": "string",
            "example": "APPROVED",
            "description": "コメントの承認状態。APPROVED, PENDING, DENIED",
            "enum": ["APPROVED", "PENDING", "DENIED"]
          },
          "id": {
            "type": "string",
            "description": "寄付ID",
            "example": "1"
          },
          "readstate": {
            "type": "string",
            "description": "コメントを読み上げ対象にするかどうか。APPROVED, PENDING, DENIED, IGNORED",
            "enum": ["APPROVED", "PENDING", "DENIED"],
            "example": "IGNORED"
          },
          "type": {
            "type": "string",
            "description": "操作対象種別。donationで固定",
            "example": "donation"
          }
        }
      },
      "trackerDelete": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "description": "削除対象の項目。event, donor, donation, runなど",
            "example": "event"
          },
          "id": {
            "type": "string",
            "description": "削除対象のID。typeに紐づくpkを指定する",
            "example": "3"
          }
        }
      },
      "errorResponse": {
        "type": "object",
        "properties": {
          "error": {
            "type": "string",
            "example": "Permission Denied"
          },
          "exception": {
            "type": "string",
            "example": ""
          }
        }
      }
    },
    "examples": {
      "donationResponse1": {
        "summary": "コメント無し",
        "value": [
          {
            "model": "tracker.donation",
            "pk": 5,
            "fields": {
              "donor": 1,
              "event": 4,
              "domain": "PAYPAL",
              "transactionstate": "COMPLETED",
              "readstate": "PENDING",
              "commentstate": "ABSENT",
              "amount": 2500.0,
              "currency": "JPY",
              "timereceived": "2022-08-13T19:44:20.472Z",
              "comment": "",
              "commentlanguage": "un",
              "pinned": false,
              "canonical_url": "https://tracker.rtain.jp/donation/5",
              "public": "Rちゃん (2500.00) 2022-08-13 19:44:20.472578+00:00",
              "donor__alias": "Rちゃん",
              "donor__alias_num": 8198,
              "donor__visibility": "ALIAS",
              "donor__canonical_url": "https://tracker.rtain.jp/donor/１",
              "donor__public": "Rちゃん"
            }
          }
        ]
      },
      "donationResponse2": {
        "summary": "コメント有り",
        "value": [
          {
            "model": "tracker.donation",
            "pk": 5,
            "fields": {
              "donor": 1,
              "event": 4,
              "domain": "PAYPAL",
              "transactionstate": "COMPLETED",
              "readstate": "PENDING",
              "commentstate": "PENDING",
              "amount": 2500.0,
              "currency": "JPY",
              "timereceived": "2022-08-13T19:44:20.472Z",
              "comment": "応援してます！",
              "commentlanguage": "un",
              "pinned": false,
              "canonical_url": "https://tracker.rtain.jp/donation/5",
              "public": "Rちゃん (2500.00) 2022-08-13 19:44:20.472578+00:00",
              "donor__alias": "Rちゃん",
              "donor__alias_num": 8198,
              "donor__visibility": "ALIAS",
              "donor__canonical_url": "https://tracker.rtain.jp/donor/１",
              "donor__public": "Rちゃん"
            }
          }
        ]
      },
      "donationResponse3": {
        "summary": "all_comments未指定時のレスポンス",
        "value": [
          {
            "model": "tracker.donation",
            "pk": 5,
            "fields": {
              "donor": 1,
              "event": 4,
              "domain": "PAYPAL",
              "transactionstate": "COMPLETED",
              "readstate": "PENDING",
              "commentstate": "PENDING",
              "amount": 2500.0,
              "currency": "JPY",
              "timereceived": "2022-08-13T19:44:20.472Z",
              "pinned": false,
              "canonical_url": "https://tracker.rtain.jp/donation/5",
              "public": "Rちゃん (2500.00) 2022-08-13 19:44:20.472578+00:00",
              "donor__alias": "Rちゃん",
              "donor__alias_num": 8198,
              "donor__visibility": "ALIAS",
              "donor__canonical_url": "https://tracker.rtain.jp/donor/１",
              "donor__public": "Rちゃん"
            }
          }
        ]
      },
      "runResponse1": {
        "summary": "ゲーム1個",
        "value": [
          {
            "model": "tracker.speedrun",
            "pk": 125,
            "fields": {
              "event": 4,
              "name": "地球防衛軍5",
              "display_name": "地球防衛軍5 DLC1&2 Any%",
              "twitch_name": "493080",
              "deprecated_runners": "M.雑炊",
              "console": "PlayStation 4",
              "commentators": "",
              "description": "",
              "starttime": "2022-08-11T03:00:00Z",
              "endtime": "2022-08-11T04:20:00Z",
              "order": 1,
              "run_time": "1:05:00",
              "setup_time": "0:15:00",
              "coop": false,
              "category": "DLC1&2 Any%",
              "release_year": 2017,
              "giantbomb_id": null,
              "runners": [166],
              "canonical_url": "https://tracker.rtain.jp/run/125",
              "public": "地球防衛軍5 DLC1&2 Any% (event_id: 4)"
            }
          }
        ]
      },
      "bidResponse1": {
        "summary": "bids",
        "value": [
          {
            "model": "tracker.bid",
            "pk": 111,
            "fields": {
              "event": 4,
              "speedrun": 138,
              "parent": null,
              "name": "プレイ中の目隠し",
              "state": "CLOSED",
              "description": "プレイ中の目隠しはどれを使いますか？",
              "shortdescription": "プレイ中の目隠しはどれを使いますか？",
              "goal": null,
              "istarget": false,
              "allowuseroptions": false,
              "option_max_length": null,
              "revealedtime": "2022-08-06T04:49:21Z",
              "biddependency": null,
              "total": 188807,
              "count": 81,
              "canonical_url": "https://tracker.rtain.jp/bid/111",
              "public": "大乱闘スマッシュブラザーズDX 目隠し アドベンチャー モード (Run) -- プレイ中の目隠し",
              "speedrun__name": "大乱闘スマッシュブラザーズDX",
              "speedrun__display_name": "大乱闘スマッシュブラザーズDX 目隠し アドベンチャー モード",
              "speedrun__twitch_name": "16282",
              "speedrun__starttime": "2022-08-11T19:59:00Z",
              "speedrun__endtime": "2022-08-11T20:29:00Z",
              "speedrun__order": 15,
              "speedrun__canonical_url": "https://tracker.rtain.jp/run/138",
              "speedrun__public": "大乱闘スマッシュブラザーズDX 目隠し アドベンチャー モード (event_id: 4)",
              "event__short": "rtaijs2022",
              "event__name": "RTA in Japan Summer 2022",
              "event__datetime": "2022-08-11T03:00:00Z",
              "event__timezone": "Asia/Tokyo",
              "event__canonical_url": "https://tracker.rtain.jp/event/4",
              "event__public": "RTA in Japan Summer 2022"
            }
          }
        ]
      }
    }
  }
}
